# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-22 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compinfo',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=16)),
                ('comp_ip', models.CharField(max_length=32)),
                ('comp_realm', models.CharField(max_length=32)),
                ('state', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
                ('port', models.IntegerField(null=True)),
                ('access_status', models.IntegerField(default=1)),
                ('access_node', models.CharField(default='', max_length=32)),
                ('service_items', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'compinfo',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16, null=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('state', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='compinfo',
            name='users',
            field=models.ManyToManyField(to='common.Users'),
        ),
    ]
