# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-11 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=16)),
                ('comp_ip', models.CharField(max_length=32)),
                ('comp_realm', models.CharField(max_length=32)),
                ('state', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
                ('port', models.IntegerField(null=True)),
                ('access_status', models.IntegerField(default=1)),
                ('access_node', models.CharField(default='', max_length=32)),
                ('service_items', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'compinfo',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_id', models.IntegerField()),
                ('compinfo_id', models.IntegerField()),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16, null=True)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('state', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
