# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-12 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='compinfo_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='members',
            name='users_id',
            field=models.IntegerField(default=1),
        ),
    ]
