# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-29 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=16, null=True)),
                ('content', models.TextField(null=True)),
                ('feedtime', models.DateField(null=True)),
                ('reply_content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
