# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200508_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='compinfo',
            name='state',
            field=models.BooleanField(default=1, max_length=1),
        ),
    ]
