# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-29 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200629_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='compinfo',
            name='Leak_scan',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedtime',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
