# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200512_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='compinfo',
            name='users',
            field=models.ManyToManyField(to='common.Users'),
        ),
    ]
