# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-09 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_compinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.BooleanField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.BooleanField(default=1, max_length=1),
        ),
    ]
