# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-25 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_compinfo_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
