# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-09 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200509_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compinfo',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
